version: "3.4"

services:
  flask:
    build:
      context: ./
    ports:
      - "5000:5000"

  jikan-rest-api:
    build:
      context: jikan-docker/v3/jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
    ports:
      - "8000:8000"
    networks:
      - default
    restart: always

  jikan-redis:
    image: redis
    restart: always
